/**
 * Property-Based Tests for Explanation Content Completeness
 * Validates that AI-generated explanations include all required components
 * 
 * Property 7: Explanation Content Completeness
 * For any explanation generated by the AI Tutor, the response must include:
 * 1. The correct answer
 * 2. Reasoning explaining why the answer is correct
 * 3. At least one citation to RBI or IIBF norms
 * 
 * **Validates: Requirements 6.3, 6.5**
 */

import fc from 'fast-check';
import { DynamoDBClient, GetItemCommand, PutItemCommand } from '@aws-sdk/client-dynamodb';
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime';
import { mockClient } from 'aws-sdk-client-mock';
import { marshall } from '@aws-sdk/util-dynamodb';
import { handler } from '../index';
import { APIGatewayProxyEvent } from 'aws-lambda';

// Mock AWS SDK
const ddbMock = mockClient(DynamoDBClient);
const bedrockMock = mockClient(BedrockRuntimeClient);

// Mock modules
jest.mock('/opt/nodejs/error-handling', () => ({
  ValidationError: class ValidationError extends Error {
    constructor(message: string) {
      super(message);
      this.name = 'ValidationError';
    }
  },
  DatabaseError: class DatabaseError extends Error {
    constructor(message: string) {
      super(message);
      this.name = 'DatabaseError';
    }
  },
  formatErrorResponse: jest.fn((error: any) => ({
    statusCode: error.name === 'ValidationError' ? 400 : 500,
    headers: { 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff' },
    body: JSON.stringify({ success: false, error: error.message }),
  })),
}));

jest.mock('/opt/nodejs/logging', () => ({
  createLogger: jest.fn(() => ({
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
  })),
}));

jest.mock('/opt/nodejs/constants', () => ({
  DYNAMODB_TABLES: {
    QUESTIONS: 'questions',
    EXPLANATION_CACHE: 'explanation_cache',
  },
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
  },
}));

describe('Property: Explanation Content Completeness', () => {
  beforeEach(() => {
    ddbMock.reset();
    bedrockMock.reset();
    jest.clearAllMocks();
  });

  /**
   * Property 7.1: Explanation includes correct answer
   * For any question, the generated explanation must include the correct answer
   * in the response.
   */
  it('should include correct answer in explanation', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          question_id: fc.uuid(),
          question_text: fc.string({ minLength: 10, maxLength: 200 }),
          correct_answer: fc.oneof(
            fc.constant('A'),
            fc.constant('B'),
            fc.constant('C'),
            fc.constant('D')
          ),
          paper: fc.oneof(
            fc.constant('JAIIB_IE_IFS'),
            fc.constant('JAIIB_PPB'),
            fc.constant('JAIIB_AFB'),
            fc.constant('JAIIB_RBWM')
          ),
        }),
        async (context: any) => {
          // Mock DynamoDB question retrieval
          ddbMock.on(GetItemCommand).resolves({
            Item: marshall({
              question_id: context.question_id,
              question_text: context.question_text,
              option_a: 'Option A text',
              option_b: 'Option B text',
              option_c: 'Option C text',
              option_d: 'Option D text',
              correct_answer: context.correct_answer,
              paper: context.paper,
              rbi_norms: ['RBI Act 1934'],
              iibf_norms: ['IIBF Banking Guide'],
            }),
          });

          // Mock Bedrock response with correct answer
          bedrockMock.on(InvokeModelCommand).resolves({
            body: new ReadableStream({
              start(controller) {
                const response = {
                  content: [
                    {
                      type: 'text',
                      text: JSON.stringify({
                        explanation_text: `The correct answer is ${context.correct_answer} because...`,
                        rbi_norms: ['RBI Act 1934, Section 45'],
                        iibf_norms: ['IIBF Banking Regulation Guide'],
                      }),
                    },
                  ],
                };
                controller.enqueue(JSON.stringify(response));
                controller.close();
              },
            }) as any,
          });

          // Mock cache put
          ddbMock.on(PutItemCommand).resolves({});

          const event: Partial<APIGatewayProxyEvent> = {
            httpMethod: 'POST',
            path: '/explanations',
            body: JSON.stringify({
              question_id: context.question_id,
              practice_set_id: fc.sample(fc.uuid(), 1)[0],
            }),
          };

          const result = await handler(event as APIGatewayProxyEvent);
          expect(result.statusCode).toBe(200);

          const body = JSON.parse(result.body);
          expect(body.success).toBe(true);
          expect(body.explanation).toBeDefined();
          expect(body.explanation.correct_answer).toBe(context.correct_answer);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 7.2: Explanation includes reasoning
   * For any question, the generated explanation must include reasoning that
   * explains why the answer is correct.
   */
  it('should include reasoning in explanation', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          question_id: fc.uuid(),
          question_text: fc.string({ minLength: 10, maxLength: 200 }),
          correct_answer: fc.oneof(
            fc.constant('A'),
            fc.constant('B'),
            fc.constant('C'),
            fc.constant('D')
          ),
          paper: fc.oneof(
            fc.constant('JAIIB_IE_IFS'),
            fc.constant('JAIIB_PPB'),
            fc.constant('JAIIB_AFB'),
            fc.constant('JAIIB_RBWM')
          ),
        }),
        async (context: any) => {
          // Mock DynamoDB question retrieval
          ddbMock.on(GetItemCommand).resolves({
            Item: marshall({
              question_id: context.question_id,
              question_text: context.question_text,
              option_a: 'Option A text',
              option_b: 'Option B text',
              option_c: 'Option C text',
              option_d: 'Option D text',
              correct_answer: context.correct_answer,
              paper: context.paper,
              rbi_norms: ['RBI Act 1934'],
              iibf_norms: ['IIBF Banking Guide'],
            }),
          });

          // Mock Bedrock response with reasoning
          const reasoningText = `The correct answer is ${context.correct_answer} because it aligns with the regulatory framework and best practices in banking.`;
          const mockResponse = {
            content: [
              {
                type: 'text',
                text: JSON.stringify({
                  explanation_text: reasoningText,
                  rbi_norms: ['RBI Act 1934, Section 45'],
                  iibf_norms: ['IIBF Banking Regulation Guide'],
                }),
              },
            ],
          };

          bedrockMock.on(InvokeModelCommand).resolves({
            body: {
              transformToString: () => JSON.stringify(mockResponse),
            } as any,
          });

          // Mock cache put
          ddbMock.on(PutItemCommand).resolves({});

          const event: Partial<APIGatewayProxyEvent> = {
            httpMethod: 'POST',
            path: '/explanations',
            body: JSON.stringify({
              question_id: context.question_id,
              practice_set_id: fc.sample(fc.uuid(), 1)[0],
            }),
          };

          const result = await handler(event as APIGatewayProxyEvent);
          expect(result.statusCode).toBe(200);

          const body = JSON.parse(result.body);
          expect(body.success).toBe(true);
          expect(body.explanation).toBeDefined();
          expect(body.explanation.explanation_text).toBeDefined();
          expect(body.explanation.explanation_text.length).toBeGreaterThan(0);
          expect(body.explanation.explanation_text).toContain('because');
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 7.3: Explanation includes RBI or IIBF citations
   * For any question, the generated explanation must include at least one
   * citation to RBI or IIBF norms.
   */
  it('should include RBI or IIBF citations in explanation', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          question_id: fc.uuid(),
          question_text: fc.string({ minLength: 10, maxLength: 200 }),
          correct_answer: fc.oneof(
            fc.constant('A'),
            fc.constant('B'),
            fc.constant('C'),
            fc.constant('D')
          ),
          paper: fc.oneof(
            fc.constant('JAIIB_IE_IFS'),
            fc.constant('JAIIB_PPB'),
            fc.constant('JAIIB_AFB'),
            fc.constant('JAIIB_RBWM')
          ),
          rbi_norms: fc.array(
            fc.string({ minLength: 5, maxLength: 100 }),
            { minLength: 1, maxLength: 3 }
          ),
          iibf_norms: fc.array(
            fc.string({ minLength: 5, maxLength: 100 }),
            { minLength: 0, maxLength: 3 }
          ),
        }),
        async (context: any) => {
          // Ensure at least one norm is present
          const hasNorms = context.rbi_norms.length > 0 || context.iibf_norms.length > 0;
          fc.pre(hasNorms);

          // Mock DynamoDB question retrieval
          ddbMock.on(GetItemCommand).resolves({
            Item: marshall({
              question_id: context.question_id,
              question_text: context.question_text,
              option_a: 'Option A text',
              option_b: 'Option B text',
              option_c: 'Option C text',
              option_d: 'Option D text',
              correct_answer: context.correct_answer,
              paper: context.paper,
              rbi_norms: context.rbi_norms,
              iibf_norms: context.iibf_norms,
            }),
          });

          // Mock Bedrock response with citations
          bedrockMock.on(InvokeModelCommand).resolves({
            body: new ReadableStream({
              start(controller) {
                const response = {
                  content: [
                    {
                      type: 'text',
                      text: JSON.stringify({
                        explanation_text: `The correct answer is ${context.correct_answer} because it aligns with regulatory requirements.`,
                        rbi_norms: context.rbi_norms.length > 0 ? context.rbi_norms : [],
                        iibf_norms: context.iibf_norms.length > 0 ? context.iibf_norms : [],
                      }),
                    },
                  ],
                };
                controller.enqueue(JSON.stringify(response));
                controller.close();
              },
            }) as any,
          });

          // Mock cache put
          ddbMock.on(PutItemCommand).resolves({});

          const event: Partial<APIGatewayProxyEvent> = {
            httpMethod: 'POST',
            path: '/explanations',
            body: JSON.stringify({
              question_id: context.question_id,
              practice_set_id: fc.sample(fc.uuid(), 1)[0],
            }),
          };

          const result = await handler(event as APIGatewayProxyEvent);
          expect(result.statusCode).toBe(200);

          const body = JSON.parse(result.body);
          expect(body.success).toBe(true);
          expect(body.explanation).toBeDefined();

          // Check that at least one citation is present
          const hasRBINorms = body.explanation.rbi_norms && body.explanation.rbi_norms.length > 0;
          const hasIIBFNorms = body.explanation.iibf_norms && body.explanation.iibf_norms.length > 0;
          expect(hasRBINorms || hasIIBFNorms).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property 7.4: Explanation completeness across all question types
   * For any question type and paper, the explanation must be complete with
   * all required components.
   */
  it('should generate complete explanations for all question types and papers', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          question_id: fc.uuid(),
          question_text: fc.string({ minLength: 10, maxLength: 200 }),
          correct_answer: fc.oneof(
            fc.constant('A'),
            fc.constant('B'),
            fc.constant('C'),
            fc.constant('D')
          ),
          paper: fc.oneof(
            fc.constant('JAIIB_IE_IFS'),
            fc.constant('JAIIB_PPB'),
            fc.constant('JAIIB_AFB'),
            fc.constant('JAIIB_RBWM')
          ),
          difficulty: fc.oneof(
            fc.constant('easy'),
            fc.constant('medium'),
            fc.constant('hard')
          ),
        }),
        async (context: any) => {
          // Mock DynamoDB question retrieval
          ddbMock.on(GetItemCommand).resolves({
            Item: marshall({
              question_id: context.question_id,
              question_text: context.question_text,
              option_a: 'Option A text',
              option_b: 'Option B text',
              option_c: 'Option C text',
              option_d: 'Option D text',
              correct_answer: context.correct_answer,
              paper: context.paper,
              difficulty_level: context.difficulty,
              rbi_norms: ['RBI Act 1934'],
              iibf_norms: ['IIBF Banking Guide'],
            }),
          });

          // Mock Bedrock response
          const mockResponse = {
            content: [
              {
                type: 'text',
                text: JSON.stringify({
                  explanation_text: `Comprehensive explanation for ${context.paper} question at ${context.difficulty} level.`,
                  rbi_norms: ['RBI Act 1934, Section 45', 'RBI Circular 2024'],
                  iibf_norms: ['IIBF Banking Regulation Guide', 'IIBF Compliance Standards'],
                }),
              },
            ],
          };

          bedrockMock.on(InvokeModelCommand).resolves({
            body: {
              transformToString: () => JSON.stringify(mockResponse),
            } as any,
          });

          // Mock cache put
          ddbMock.on(PutItemCommand).resolves({});

          const event: Partial<APIGatewayProxyEvent> = {
            httpMethod: 'POST',
            path: '/explanations',
            body: JSON.stringify({
              question_id: context.question_id,
              practice_set_id: fc.sample(fc.uuid(), 1)[0],
            }),
          };

          const result = await handler(event as APIGatewayProxyEvent);
          expect(result.statusCode).toBe(200);

          const body = JSON.parse(result.body);
          expect(body.success).toBe(true);
          expect(body.explanation).toBeDefined();

          // Verify all required fields are present
          expect(body.explanation.correct_answer).toBe(context.correct_answer);
          expect(body.explanation.explanation_text).toBeDefined();
          expect(body.explanation.explanation_text.length).toBeGreaterThan(0);
          expect(Array.isArray(body.explanation.rbi_norms)).toBe(true);
          expect(Array.isArray(body.explanation.iibf_norms)).toBe(true);
          expect(body.explanation.rbi_norms.length + body.explanation.iibf_norms.length).toBeGreaterThan(0);
        }
      ),
      { numRuns: 100 }
    );
  });
});
